create table if not exists public.books
(
    id  integer generated by default as identity
        primary key,
    isbn   varchar(16),
    title  varchar(128),
    author varchar(64),
    price  numeric
    );
